CREATE TABLE User (
id INT AUTO_INCREMENT NOT NULL,
username VARCHAR(50) NOT NULL,
password VARCHAR(50) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE Wishlist (
id INT AUTO_INCREMENT NOT NULL,
author VARCHAR(50) NOT NULL,
title VARCHAR(100) NOT NULL,
favorite BOOLEAN DEFAULT false
have_read BOOLEAN DEFAULT false
PRIMARY KEY (id)
-- FOREIGN KEY ASSOC. WITH USER
);

CREATE TABLE Current (
id INT AUTO_INCREMENT NOT NULL,
author VARCHAR(50) NOT NULL,
title VARCHAR(100) NOT NULL,
favorite BOOLEAN DEFAULT false
PRIMARY KEY (id)
-- FOREIGN KEY ASSOC. WITH USER
);

CREATE TABLE Complete (
id INT AUTO_INCREMENT NOT NULL,
author VARCHAR(50) NOT NULL,
title VARCHAR(100) NOT NULL,
favorite BOOLEAN DEFAULT false
have_read BOOLEAN DEFAULT true
PRIMARY KEY (id)
-- FOREIGN KEY ASSOC. WITH USER
);